### ISSUE TITLE
Install without Carthage

### ISSUE THREAD

**Issue by wigging** [sindresorhus/LaunchAtLogin#1]
Can you provide instructions in the README on how to install this without using Carthage or CocoaPods?

**Comment by sindresorhus** [comment]
I'll try to add some docs when I have time. 

The only difference from how you would usually add a framework manually (That's Google-able if you don't already know) is that you need to change the path from `./Carthage/Build/Mac/LaunchAtLogin.framework/Resources/copy-helper.sh` to the correct path where the framework is placed in your project.

**Comment by wigging** [comment]
I'll search for guides on how to manually install a framework but it would be helpful if you could provide the steps in the README.

**Comment by Ghosty141** [comment]
@wigging I just saw this issue and I'm wondering if you got it to work with Carthage?

**Comment by wigging** [comment]
@Ghosty141 No, I have not been able to run it without Carthage. Hopefully the developer will update the README with the necessary steps.

**Comment by Ghosty141** [comment]
@sindresorhus It would be great if you could make it available on cocoapods since it's one of the most used dependancy managers!

**Comment by sindresorhus** [comment]
@Ghosty141 Sorry, no. I don't like or use CocoaPods. It's too invasive. I will add SPM support when Swift 4 is out.

**Comment by Ghosty141** [comment]
@sindresorhus Alright, thanks for the info!

**Comment by kajensen** [comment]
+1 for non-carthage

**Comment by sindresorhus** [comment]
I've decided not to do this. I never manually embed frameworks myself, so I'm not interested in supporting this.
