### ISSUE TITLE
Upload Symbols Failed – The archive did not include a dSYM for the LaunchAtLoginHelper.app

### ISSUE THREAD

**Issue by frogg** [sindresorhus/LaunchAtLogin#106]
When I upload my archive to App Store Connect I get the following error message:

## Upload Symbols Failed
The archive did not include a dSYM for the LaunchAtLoginHelper.app with the UUIDs […, …]. Ensure that the archive's dSYM folder includes a DWARF file for LaunchAtLoginHelper.app with the expected UUIDs.

Does anyone know what this means and how I can fix it?

**Comment by sindresorhus** [comment]
Duplicate of #104
