### ISSUE TITLE
'SMCopyAllJobDictionaries' was deprecated in OS X 10.10

### ISSUE THREAD

**Issue by tomatoTom** [sindresorhus/LaunchAtLogin#12]
`'SMCopyAllJobDictionaries' was deprecated in OS X 10.10`

warning in LaunchAtLogin.swift (line9).

**Comment by sindresorhus** [comment]
Apple deprecated that API without providing an alternative. I plan to use it as long as it's available. There are workarounds I can implement if Apple ever removes the API, so rest assured, this module will be made to work even then.

**Comment by sindresorhus** [comment]
Moved this to the readme: https://github.com/sindresorhus/LaunchAtLogin#faq

**Comment by sindresorhus** [comment]
I just noticed that the `SMCopyAllJobDictionaries` header says:

> For the specific use of testing the state of a login item that may have been enabled with SMLoginItemSetEnabled() in order to show that state to the user, this function remains the recommended API. A replacement API for this specific use will be provided before this function is removed.

I'm not sure if this was always there or if it's new.
