### ISSUE TITLE
Is code signing necessary?

### ISSUE THREAD

**Issue by B00jan** [sindresorhus/LaunchAtLogin#14]
Im trying to test the app without signing the app and it is not working. Is it necessary to sign it?

**Comment by deadcoder0904** [comment]
Yes I was also wondering the same thing. 

Another question: Does this work in Development, i.e, without putting it in Applications folder?

**Comment by sindresorhus** [comment]
Your questions are about launching at login in general and not specifically about this module. `LaunchAtLogin` just simplifies the process.

**Comment by B00jan** [comment]
I've noticed this error in my console. Do you now what am i doing wrong?
Could not locate login item com.my.project-LaunchAtLoginHelper in the caller's bundle
Could not enable login item: com.my.project-LaunchAtLoginHelper: 3: No such process

**Comment by deadcoder0904** [comment]
@B00jan I got this too before and thank god I did save [this StackOverflow answer](https://stackoverflow.com/a/41217410/6141587).

I didn't know if it made it work but as sindresorhus has said [here](https://github.com/sindresorhus/LaunchAtLogin/issues/5#issuecomment-338764056) it gives me this exact response. I'll test it later tonight & post the solution if it works :)

**Comment by sindresorhus** [comment]
@B00jan Look in the exported app bundle if you have the helper app included and that it uses that bundle ID (check its Info.plist).

**Comment by B00jan** [comment]
No helper app included. So i guess something went wrong when importing pod in my project.

**Comment by sindresorhus** [comment]
It should not be checked.

**Comment by B00jan** [comment]
cp: /Users/ME/Library/Developer/Xcode/DerivedData/manager-goquldsquoncdqeegtdrwisfiodm/Build/Products/Debug/DSManager.app/Contents/Frameworks/LaunchAtLogin.framework/Resources/LaunchAtLoginHelper.app: No such file or directory
: no identity found
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

I have done everything from start, this is the error that i'm getting now. Sory for this much questions about something that is maybe obvious for you. I'm new at macOs programing, so some of my questions are probably stupid.

**Comment by deadcoder0904** [comment]
I get [the same error](https://github.com/sindresorhus/LaunchAtLogin/issues/13#issuecomment-417555596) & posted it on another issue. If you do find a solution plz post it :)

**Comment by B00jan** [comment]
@deadcoder0904  Of course!

**Comment by deadcoder0904** [comment]
@B00jan I used this project with Carthage & it worked. Here's a sample link that worked - https://github.com/deadcoder0904/LaunchAtLoginCart

**Comment by B00jan** [comment]
@deadcoder0904 tried it just now, and everything works.Thank you!.
Code signing isn't necessary for launch at login to work.

**Comment by deadcoder0904** [comment]
@B00jan Working with CocoaPods too. Find a solution [here](https://github.com/sindresorhus/LaunchAtLogin/issues/13#issuecomment-418700592) :)
