### ISSUE TITLE
v2.2.1 is not released to CocoaPods

### ISSUE THREAD

**Issue by frankdilo** [sindresorhus/LaunchAtLogin#15]
Hey man, just wanted to let you know that you forgot to push 2.2.1 to CocoaPods. The latest listed version [there](https://cocoapods.org/pods/LaunchAtLogin) is 2.2.0.

**Comment by frankdilo** [comment]
CocoaPods does not work at all.

**Comment by sindresorhus** [comment]
Fixed now, sorry about the delay :)
