### ISSUE TITLE
Helper needs com.apple.security.automation.apple-events entitlement

### ISSUE THREAD

**Issue by DivineDominion** [sindresorhus/LaunchAtLogin#24]
Trying the LaunchAtLogin helper in another app of mine today. Got this when I triggered the setting:

> Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: de.christiantietze.WorkBreak-LaunchAtLoginHelper, PID[2079], auid: 501, euid: 501, binary path: '/Applications/Move!.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/MacOS/LaunchAtLoginHelper'}, REQ:{ID: com.apple.appleeventsd, PID[51], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}

Looks like the helper needs `com.apple.security.automation.apple-events` hardened runtime resource access.

**Comment by DivineDominion** [comment]
Am trying this out; let's see how this goes.

**Comment by sindresorhus** [comment]
I don’t see why it would need that. It’s not using AppleEvents in any way.

**Comment by DivineDominion** [comment]
Adding this to the entitlements didn't change the Console output. Maybe it's a false-positive for my app using global event monitors. I'll try that.

**Comment by DivineDominion** [comment]
Neither change seems to resolve the message. I'll try with another app later 🤔

**Comment by Iomegan** [comment]
Have you been able to resolve the issue?

**Comment by NeomMob** [comment]
I am facing the same issue and I am wondering if one of you found a solution for this.

**Comment by sindresorhus** [comment]
This might be fixed in https://github.com/sindresorhus/LaunchAtLogin/releases/tag/v3.0.1

**Comment by sindresorhus** [comment]
I'd recommend switching to SPM for this, which should have fewer problems: https://github.com/sindresorhus/LaunchAtLogin/releases/tag/v4.0.0
