### ISSUE TITLE
Deployment target can be set to OS X 10.9

### ISSUE THREAD

**Issue by kaatt** [sindresorhus/LaunchAtLogin#29]
I cloned the repo and set the deployment target to OS X 10.9. It builds without issues. Not tested it on 10.9 but I guess it should work.

Why not lower this requirement so that more people can use this for their projects?

**Comment by sindresorhus** [comment]
Because then I have to support and test on such old systems too. You are free to change the deployment target yourself if you need. I target macOS 10.12 in all my packages and I don't intend to change that.
