### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by inket** [sindresorhus/LaunchAtLogin#3]
This looks too similar to https://github.com/inket/StartAtLogin - mind explaining?

**Comment by sindresorhus** [comment]
Yeah, seems we both were frustrated with how many steps you have to go through to get this kind of functionality set up. I guess the biggest benefit of this project compared to yours is that users only have to include a single line in their "run script".

**Comment by inket** [comment]
I hope you're happy with yourself!

I have to tell you though, you missed a crucial thing when copy-pasting.

**Comment by sindresorhus** [comment]
> I have to tell you though, you missed a crucial thing when copy-pasting.

Maybe I missed it, because, uhm, I didn't copy-paste.
