### ISSUE TITLE
File size for LaunchAtLoginHelper

### ISSUE THREAD

**Issue by j1mie** [sindresorhus/LaunchAtLogin#31]
Hi there, noticing when looking at "Show Package Contents" for my application and then going to `Contents/Frameworks/LaunchAtLogin.framework/Versions/A/Resources/LaunchAtLoginHelper` - the file is 10.4mb. Is this correct, or am I importing it incorrectly? Thanks!

**Comment by sindresorhus** [comment]
It's because Swift bundles required runtime libraries. Not much we can do about that.

When you target macOS 10.14.4 or later in your app, you could set that target in LaunchAtLogin too and then it will not bundle the Swift runtime libraries, but instead use the ones that come with the system.
