### ISSUE TITLE
Apps not showing up in System Preferences Login Items

### ISSUE THREAD

**Issue by chrenn** [sindresorhus/LaunchAtLogin#32]
Apps using LaunchAtLogin are not showing up in System Preferences › Users & Groups › Login Items, while apps using approaches not based on the ServiceManagement framework do (e.g. using [LoginServiceKit](https://github.com/Clipy/LoginServiceKit)).

<img width="762" alt="Bildschirmfoto 2020-01-17 um 15 00 25" src="https://user-images.githubusercontent.com/30233933/72618152-ca1ce880-393a-11ea-8e0e-5229b2f1e9ff.png">

Using ServiceManagement seems to be recommended by Apple tho, as also seen in the compiler warning for _kLSSharedFileListSessionLoginItems_.

Is there any insight on this? Seems to me like a bug on Apple's side.

**Comment by sindresorhus** [comment]
[This is the expected behavior](https://stackoverflow.com/a/15104481/64949), unfortunately. You can complain to Apple => https://feedbackassistant.apple.com/welcome

---

> Using ServiceManagement seems to be recommended by Apple tho, as also seen in the compiler warning for kLSSharedFileListSessionLoginItems.

It's not possible to use that in sandboxed apps, for example, for apps on the App Store.
