### ISSUE TITLE
Code Signature Invalid. LaunchAtLogin crashes and starts again every minute

### ISSUE THREAD

**Issue by zaplitny** [sindresorhus/LaunchAtLogin#35]
**LaunchAtLoginHelper.app** crashes and restarts infinitely after enabling it in parent app. I tried everything: clean derived data, ensured there's no build anywhere, restart my Mac

Signed with Developer ID. Notarization doesn't help

<img width="956" alt="Screen Shot 2020-03-22 at 16 09 57" src="https://user-images.githubusercontent.com/756746/77250532-ae470300-6c59-11ea-8759-e7c8370b1723.png">

<img width="737" alt="Screen Shot 2020-03-22 at 16 28 22" src="https://user-images.githubusercontent.com/756746/77250660-87d59780-6c5a-11ea-880b-50f592143bcb.png">

**MacOS**: 10.15.3
**Xcode**: 11.3.1
**LaunchAtLogin**: 3.0

> Process:               LaunchAtLoginHelper [741]
> Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/myapp-brgstowqtjknyydmuxizgaocwzvk/Build/Products/Debug/myapp.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/MacOS/LaunchAtLoginHelper
> Identifier:            LaunchAtLoginHelper
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           LaunchAtLoginHelper [741]
> User ID:               501
> 
> Date/Time:             2020-03-22 16:06:18.630 +0300
> OS Version:            Mac OS X 10.15.3 (19D76)
> Report Version:        12
> Bridge OS Version:     4.2 (17P3050)
> Anonymous UUID:        7B9504BD-E7E4-32D2-F641-BB2C2FC5CC69
> 
> Time Awake Since Boot: 59 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        Unknown
> 
> Exception Type:        EXC_CRASH (Code Signature Invalid)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY

**Comment by jeremycote** [comment]
I've got the same issue. Did you find a solution? Thanks.

**Comment by sindresorhus** [comment]
I'd recommend switching to SPM for this, which should have fewer problems: https://github.com/sindresorhus/LaunchAtLogin/releases/tag/v4.0.0

**Comment by amlestin** [comment]
Solution to LaunchAtLogin infinitely crashing and respawning each minute: https://stackoverflow.com/questions/27876046/error-when-enabling-auto-login-of-macos-app-using-a-helper
