### ISSUE TITLE
Invalid bundle name: bundle ID must not contain tools provided by Apple

### ISSUE THREAD

**Issue by demianturner** [sindresorhus/LaunchAtLogin#39]
I submitted an app last week with your wonderful LaunchAtLogin, no issues, went straight through.  Yesterday I added the framework to a second app and it promptly failed AppStore validation with the following error:

![](https://i.imgur.com/N9g0dnd.png)

I checked the . dSYM and indeed it has a bundle ID that starts with `com.apple`.  Easy fix then.  In my case because I needed the app to process quickly, I just removed the dSYM.

**Comment by sindresorhus** [comment]
That's a weird error. I have not encountered that in my apps which use `LaunchAtLogin`. Seems like this is either an Xcode or Carthage problem. `LaunchAtLogin` is not in control of the bundle ID of dsym.

**Comment by sindresorhus** [comment]
Can you try the latest version and see if it fixes anything?

https://github.com/sindresorhus/LaunchAtLogin/releases/tag/v3.0.1

**Comment by demianturner** [comment]
Sure, I need to release in a few days, will let you know.

**Comment by demianturner** [comment]
I just did a release with your latest update and it passed MAS validation no probs, nice one - thanks! Closing the issue.
