### ISSUE TITLE
Package has no Package.swift manifest for version 3.0.0

### ISSUE THREAD

**Issue by leits** [sindresorhus/LaunchAtLogin#40]
<img width="727" alt="зображення" src="https://user-images.githubusercontent.com/12017826/84148760-1989bf80-aa68-11ea-9ee2-723bc4d4d948.png">

**Comment by sindresorhus** [comment]
This package does not yet support Swift Package Manager: https://github.com/sindresorhus/LaunchAtLogin/issues/4
