### ISSUE TITLE
code object is not signed at all

### ISSUE THREAD

**Issue by frogg** [sindresorhus/LaunchAtLogin#44]
Hello,

I'm encountering some problems with LaunchAtLogin that I can't figure out by myself:
I've integrated the framework using Carthage, added the script, and now whenever I try to compile I get this error:
```
code object is not signed at all
In subcomponent: Contents/Library/LoginItems/LaunchAtLoginHelper.app
```

Any ideas what I could try to solve this issue?

**Comment by sindresorhus** [comment]
There are some tips in the readme. You could also try the open PR that adds Swift Package Manager support, which should work more reliably.

**Comment by xta** [comment]
Getting this error as well: `code object is not signed at all`. Due to this error, I cannot archive/build the app.

I looked into [Swift Package Manager PR](https://github.com/SergeyKuryanov/LaunchAtLogin/tree/4_swift_package_manager_support#swift-package-manager) and that requires Xcode 12? Current GM Xcode is only v11

@frogg were you able to get this working? 

Thanks

**Comment by paxos** [comment]
I got this running with a custom sign script (Xcode 11):

```
LOCATION="${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"
IDENTITY=${EXPANDED_CODE_SIGN_IDENTITY_NAME}

codesign --verbose --force -o runtime --sign "$IDENTITY" "$LOCATION/../Library/LoginItems/LaunchAtLoginHelper.app"
```

**Comment by frogg** [comment]
> Getting this error as well: `code object is not signed at all`. Due to this error, I cannot archive/build the app.
> 
> I looked into [Swift Package Manager PR](https://github.com/SergeyKuryanov/LaunchAtLogin/tree/4_swift_package_manager_support#swift-package-manager) and that requires Xcode 12? Current GM Xcode is only v11
> 
> @frogg were you able to get this working?
> 
> Thanks

Managed to get this working with the mentioned [Swift Packet Manager Branch](https://github.com/SergeyKuryanov/LaunchAtLogin/tree/4_swift_package_manager_support#swift-package-manager). Thanks for the great work @SergeyKuryanov!

Xcode 12 is available [here](https://developer.apple.com/download/) btw.

**Comment by sindresorhus** [comment]
Good to hear. That branch is now shipping in v4. https://github.com/sindresorhus/LaunchAtLogin/releases/tag/v4.0.0
