### ISSUE TITLE
Mac Catalyst Login Item

### ISSUE THREAD

**Issue by frogg** [sindresorhus/LaunchAtLogin#46]
Hello! Has anyone implemented this project with a Mac Catalyst app so far?

Would be grateful for any tips!

**Comment by tommycarpi** [comment]
I'd be interested too

**Comment by sindresorhus** [comment]
I don't plan to support Catalyst.

It would also not be possible to support it in the future anyway: https://github.com/sindresorhus/LaunchAtLogin/issues/76
