### ISSUE TITLE
Don't know where to add script

### ISSUE THREAD

**Issue by RoyRao2333** [sindresorhus/LaunchAtLogin#51]
I've installed this framework with Swift Package Manager and included it in my project. However, I can't seem to make it work after I set .isEnabled = true since I restart my system and nothing happened. I followed the instructions to remove Xcode's Derived Data and double-checked there're no duplicated files of my app. So I figured this might caused by adding the script mistakenly.

Here're steps I took:
1. Targets(AppName) -> Build Phases -> Run Script
2. I left everything else as default and copied  **"${BUILT_PRODUCTS_DIR}/LaunchAtLogin_LaunchAtLogin.bundle/Contents/Resources/copy-helper-swiftpm.sh" (with quote)** to the textfield below to replace **# Type a script or drag a script file from your workspace to insert its path.**
3. In my project, import framework and set .isEnabled = true. Build and run, then restart system

I don't know where did I get wrong, can anybody give me some advice? Much appreciated.

**Comment by sindresorhus** [comment]
Make sure you didn't miss this part:

> below "Embed Frameworks" in "Build Phases"

**Comment by RoyRao2333** [comment]
Hi! Thanks for answering!
The thing is, **Embed Frameworks** seems not exists since Xcode 12 and maybe renamed to **Dependencies**? So you're saying that I should add this framework into **Dependencies** phase as well? Waiting for your reply!

**Comment by RoyRao2333** [comment]
> Make sure you didn't miss this part:
> 
> > below "Embed Frameworks" in "Build Phases"

Hi! Thanks for answering!
The thing is, **Embed Frameworks** seems not exists since Xcode 12 and maybe renamed to **Dependencies**? So you're saying that I should add this framework into **Dependencies** phase as well? Waiting for your reply!

**Comment by RoyRao2333** [comment]
> Make sure you didn't miss this part:
> 
> > below "Embed Frameworks" in "Build Phases"

Hi! Thanks for answering!
The thing is, **Embed Frameworks** seems not exists since Xcode 12 and maybe renamed to **Dependencies**? So you're saying that I should add this framework into **Dependencies** phase as well? 
I'm also sending a screenshot to your email, thanks again and I'll be waiting for your reply!

**Comment by RoyRao2333** [comment]
> Make sure you didn't miss this part:
> 
> > below "Embed Frameworks" in "Build Phases"

Hi there! I've found some logs keep showing in my building output:
**[logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags**
Does this have any connection with my problem? Thanks!

**Comment by UzumakiAlfredo** [comment]
I have also not figured this out!
