### ISSUE TITLE
Compile LaunchAtLoginHelper.app to Universal app?

### ISSUE THREAD

**Issue by honghaoz** [sindresorhus/LaunchAtLogin#53]
I'm using SPM to integrate this package, looks like the `LaunchAtLoginHelper.app` bundled in `Contents/Library/LoginItems` is still an Intel-based app. 

Do you think it is a good idea to recompile it to a universal app? Thanks!

**Comment by sindresorhus** [comment]
Yeah, I will get to it at some point, but it really does not matter as it's just a tiny launcher app.
