### ISSUE TITLE
Rewrite LaunchAtLoginHelper in Objective-C

### ISSUE THREAD

**Issue by tbodt** [sindresorhus/LaunchAtLogin#54]
There are only 25 lines of code compiled into the app. The result is a 47kb app binary and 10mb of swift standard libraries that must be included for some reason. Rewriting in Objective-C would reduce the size by over 99%.

**Comment by sindresorhus** [comment]
If your app targets macOS 10.14.4 or later, LaunchAtLogin will not include the Swift Standard Libraries. I'm not interested in rewriting it in Objective-C.
