### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Znow** [sindresorhus/LaunchAtLogin#6]
Hi @sindresorhus 

I've been following your installation instructions, point by point. But cant seem to get it working out of the box.

I got the Carthage stuff installed, in the root folder.

But when I add "import LaunchAtLogin" to my AppDelegate.swift, it cannot see the library, and thus I cannot build the project.

Thanks in advance,

Regards

**Comment by sindresorhus** [comment]
Sounds like the Carthage thing was not set up correctly. See: https://www.google.co.th/search?q=carthage+%22Library+not+loaded%22&oq=carthage+%22Library+not+loaded%22&aqs=chrome..69i57j0l2.2159j0j1&sourceid=chrome&ie=UTF-8

**Comment by Znow** [comment]
@sindresorhus - Thanks, got that part working. But when I run the project, it outputs "Could not enable login item Project.Project-LaunchAtLoginHelper: 3: No such process"


I have defined "LaunchAtLogin.isEnabled = true" in the "applicationDidFinishLaunching" function in AppDelegate.swift

Regards

**Comment by Znow** [comment]
@sindresorhus Got it working at last, thanks :-)

Do you know, if its possible to force the app to start on login, even when a new user is created on the system? So it does require to log onto the user, and start the application, to get it to autostart

**Comment by sindresorhus** [comment]
> Got it working at last, thanks :-)

What was the problem? (Useful to have it documented here if any other user encounters the same issue)

> Do you know, if its possible to force the app to start on login, even when a new user is created on the system? So it does require to log onto the user, and start the application, to get it to autostart

No, that's not possible for sandboxed apps.
