### ISSUE TITLE
helper crashing: `The code signature is not valid: The operation couldn’t be completed. (OSStatus error -67030.)`

### ISSUE THREAD

**Issue by godbout** [sindresorhus/LaunchAtLogin#64]
happens on Big Sur 11.5.2 and Catalina 10.15.7.

Xcode 12.5.1 and 12.4.
Swift 5.4.2 and 5.3.2.
targeting macOS 10.15.
LaunchAtLogin 4.1.0.

from `console.log`:
```
Process:               LaunchAtLoginHelper [19238]
Path:                  /Applications/kindaVim.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/MacOS/LaunchAtLoginHelper
Identifier:            LaunchAtLoginHelper
Version:               1.0.1 (2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           LaunchAtLoginHelper [19238]
User ID:               501

Date/Time:             2021-08-23 01:45:21.795 +0800
OS Version:            macOS 11.5.2 (20G95)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        DE278BD3-EA41-0AA3-ED68-FC6386296036


Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [19238]

Application Specific Information:
dyld: launch, running initializers
/usr/lib/libSystem.B.dylib
The code signature is not valid: The operation couldn’t be completed. (OSStatus error -67030.)
```

that looks like this closed issue https://github.com/sindresorhus/LaunchAtLogin/issues/35 but as advised, i'm using `SPM`, not `Carthage`.

what i've tried:
* made sure i don't have other copies of my app around (confirmed by `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump|grep .kindaVim.app`)
* deleted `DerivedData`
* set `Build Active Architecture Only` to `NO`
* set `Build Active Architecture Only` to `YES`
* thoughts and prayers
* increased build number irrationally
* cried in the shower
* switched from manual signing + Developer ID to automatic signing

any hint on where i may be fucking *p?

**Comment by sindresorhus** [comment]
This is usually caused by having multiple certificates of the same type in the keychain. See the other open issues.

**Comment by godbout** [comment]
bingo. learning everyday. thanks for the Swift (hehe) response!
