### ISSUE TITLE
Where to add script?

### ISSUE THREAD

**Issue by RoyRao2333** [sindresorhus/LaunchAtLogin#68]
Hi! [After nearly one year](https://github.com/sindresorhus/LaunchAtLogin/issues/51#issue-745326568) and I found that README.md has been updated:
> Add a new “Run Script Phase” below (not into) “Copy Bundle Resources” in “Build Phases” with the following

Bear with me but I'm still confused about how can I add this script? 😓

Here's what I've done:

![image](https://user-images.githubusercontent.com/31413093/142998965-d8d5a72d-ab51-4993-86ca-a13453e69d81.png)

Don't know if I'm doing this right... Does this mean that I can continue to use this framework or am I missing something? Thanks for your patience!

**Comment by sindresorhus** [comment]
I'm honestly not sure what you are confused about? The description is pretty clear and you have done what it said.

**Comment by RoyRao2333** [comment]
> I'm honestly not sure what you are confused about? The description is pretty clear and you have done what it said.

Sorry for bothering you but I'm not quite familiar with scripts and I need to make sure if I'm doing this right. 😓 Especially not sure if the quotes ("") need to exist...

But since
> ...and you have done what it said.

Then I think I can proceed to my project. Thanks for your reply!

**Comment by sindresorhus** [comment]
> Especially not sure if the quotes ("") need to exist...

They do. That's why they are there.

**Comment by sindresorhus** [comment]
What you have done looks correct to me.

**Comment by RoyRao2333** [comment]
> What you have done looks correct to me.

Thanks, it worked! You really saved my day!
