### ISSUE TITLE
Not working with intel Mac.

### ISSUE THREAD

**Issue by GamaTellez** [sindresorhus/LaunchAtLogin#79]
The same app but LaunchAtLogin only works on apple silicon Macs and not in intel.

**Comment by GamaTellez** [comment]
UPDATE: It is still not working on my Mac intel 2021 but it is working on other ones. Still looking into it...

**Comment by sindresorhus** [comment]
Sounds like an issue with your build. I'm using this package in production for a 8+ apps without any issues. There's also no actionable information in this report.

https://github.com/sindresorhus/LaunchAtLogin#my-app-doesnt-launch-at-login-when-testing
