### ISSUE TITLE
Signing for "LaunchAtLogin_LaunchAtLogin" requires a development team in xcode 14

### ISSUE THREAD

**Issue by arielelkin** [sindresorhus/LaunchAtLogin#85]
Hello, 

My archives fail on Xcode 14.1 with this error: 

```
~/myapp/derived_data/SourcePackages/checkouts/LaunchAtLogin/Package.swift: error: Signing for "LaunchAtLogin_LaunchAtLogin" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'LaunchAtLogin_LaunchAtLogin' from project 'LaunchAtLogin')
```

I have a development team selected in my target's Signing and Capabilities section...

**Comment by ukushu** [comment]
This is absolultely sure issue of your project or your XCode, but not of this package.

Try to update XCode to 14.2 

and doublecheck the following settings: 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qJMyj.png

**Comment by 342261733** [comment]
same problem
