### ISSUE TITLE
Carthage isn't importing properly?

### ISSUE THREAD

**Issue by abey** [sindresorhus/LaunchAtLogin#9]
I followed your steps and installed this. But, when I Cmd+click LaunchAtLogin from my class, it just shows this instead of proper data. 

Did I miss something?

![screen shot 2018-05-29 at 5 00 45 pm](https://user-images.githubusercontent.com/11465329/40691788-cd8090f8-6362-11e8-90d7-b84729ca70c8.png)

**Comment by sindresorhus** [comment]
Can you confirm you're using the Swift 4.1 and latest Carthage and LaunchAtLogin version?

This is what I get:

<img width="357" alt="screen shot 2018-05-30 at 10 08 19" src="https://user-images.githubusercontent.com/170270/40696774-673b4f6a-63f1-11e8-9e99-a0a1d0dd15ad.png">

**Comment by abey** [comment]
@sindresorhus Thanks for responding! 
I just verified that I'm using the latest versions. 

I wonder if it's because of any installation/setup errors. Can you confirm if this is how the build phase script should look like?
![screen shot 2018-05-29 at 8 29 11 pm](https://user-images.githubusercontent.com/11465329/40697470-2c784c7e-637f-11e8-9289-b7deb1cd78a4.png)

I also did `carthage build` and `carthage update` to make sure that I didn't miss anything. Are there any steps that I should follow? 

Thanks!

**Comment by sindresorhus** [comment]
Yes, that looks correct. Also, make sure you have built the project at least once. The generated interface won't show correctly if not. Other than that, I don't really know. You're the first oen with this issue.

Does this module work in practice though, even though it's not showing the interface? Does `LaunchAtLogin.isEnabled = true` work?
