### ISSUE TITLE
Is there some way to enable it by default for Mac apps outside the AppStore?

### ISSUE THREAD

**Issue by alvarokrn** [sindresorhus/LaunchAtLogin#90]
Just that, I wonder if there exists some way to enable it by default for Mac apps outside the AppStore?

**Comment by sindresorhus** [comment]
There is no technical limitation, even for the App Store. It's just that Apple will reject the app if you do. So outside the App Store, you can do it if you want, but it may annoy users.

**Comment by sindresorhus** [comment]
Set `LaunchAtLogin.isEnabled = true` at launch.

**Comment by alvarokrn** [comment]
Thanks!
