### ISSUE TITLE
Invalid Provisioning Profile Signature

### ISSUE THREAD

**Issue by mixtly87** [sindresorhus/LaunchAtLogin#91]
When trying to upload macOS app to AppStore I get an error:

Invalid Provisioning Profile Signature. The provisioning profile included in the bundle XYZ [XYZ.pkg/Payload/MyApp.app] cannot be used to submit apps to the Mac App Store until it has a valid signature from Apple. For more information, visit the macOS Developer Portal. (ID: #####)

<img width="727" alt="s1" src="https://user-images.githubusercontent.com/15709777/236609222-347c1d99-6b0c-437f-b124-fc4189457013.png">

Before that when Xcode asks me to set provisioning profile, there is no option for LaunchAtLoginHelper.app

<img width="542" alt="Screenshot 2023-05-05 at 01 50 23" src="https://user-images.githubusercontent.com/15709777/236355685-1f968518-ff10-455b-8a85-ddf10a5d6326.png">

Is there a way to fix this issue? I would like to distribute the app on official MacAppStore which means it should be sandboxed.

**Comment by sindresorhus** [comment]
The error is not related to LaunchAtLogin.

**Comment by mixtly87** [comment]
You're right. I was mislead. Closing.
