### ISSUE TITLE
Platform filter to exclude iOS in xcode multiplatform targets

### ISSUE THREAD

**Issue by tonyfahrion** [sindresorhus/LaunchAtLogin#94]
Hi,

It would be very cool if the package came with a platform filter in the package description to exclude it to build for iOS as well. In a multi-platform setup I am currently unable to use the xcode preview because I can't limit the package to build for the iOS preview environment.

Excluding it for the actual build works.

Would a platform filter help here?

Thank you very much for this great package 👍

**Comment by sindresorhus** [comment]
It's already defined to only be available on macOS: https://github.com/sindresorhus/LaunchAtLogin/blob/7ad6331f9c38953eb1ce8737758e18f7607e984a/Package.swift#L6-L8

**Comment by tonyfahrion** [comment]
Oh my bad, I missed this line 🙈

Thank you sindresorhus 🙏 then it seems to be a bug in xcodes preview 🤔
